# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.video_service:
        class: AppBundle\Services\VideoService
        arguments: ['@logger', '@service_container']
