app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Static:homepage }
    methods:  [GET]

app_new_exam:
    path:     /create
    defaults: { _controller: AppBundle:Static:newExam }
    methods:  [GET|POST]

app_stop_exam:
    path:     /exam/{examName}/stop
    defaults: { _controller: AppBundle:Static:stopExam }
    methods:  [POST]

app_display_exam:
    path:     /exam/{examName}
    defaults: { _controller: AppBundle:Static:displayExam }
    methods:  [GET]

app_display_video:
    path:     /exam/{examName}/video/{etudiant}
    defaults: { _controller: AppBundle:Static:displayVideo }
    methods:  [GET]

app_pending_exam:
    path:     /pendingExam/{id}
    defaults: { _controller: AppBundle:Static:pendingExam }
    methods:  [GET]

app_delete_exam:
    path:     /exam/{examName}/deleteExam
    defaults: { _controller: AppBundle:Static:deleteExam }
    methods:  [POST]

app_logged_students:
    path:     /exam/{examName}/loggedStudents
    defaults: { _controller: AppBundle:Static:getLoggedStudents }
    methods:  [POST]

app_share_exam:
    path:     /exam/{examName}/share
    defaults: { _controller: AppBundle:Static:shareExam }
    methods:  [GET]

app_share_exam_allow:
    path:     /exam/{examName}/share/{userId}/allow
    defaults: { _controller: AppBundle:Static:allowUser }
    methods:  [GET]

app_share_exam_disallow:
    path:     /exam/{examName}/share/{userId}/disallow
    defaults: { _controller: AppBundle:Static:disallowUser }
    methods:  [GET]