app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Static:homepage }
    methods:  [GET]

app_new_exam:
    path:     /create
    defaults: { _controller: AppBundle:Static:newExam }
    methods:  [GET]

app_display_exam:
    path:     /exam/{examName}
    defaults: { _controller: AppBundle:Static:displayExam }
    methods:  [GET]

app_display_video:
    path:     /exam/{examName}/video/{etudiant}
    defaults: { _controller: AppBundle:Static:displayVideo }
    methods:  [GET]

